### PR TITLE
quotes fix

### LINKED ISSUE #1: bug with multi-carets
1. copy the following text to Cud editor (html lexer) and place multi-carets like this:

```html
<a class=| ></a>
<a class=| ></a>
```

2. insert one double-quotes char -> `"`
3. press ctrl+space
4. choose `accordion`

you will see that  double-quotes char was replaced and everything after it!

image

### LINKED ISSUE #22: Bug with multi-carets call - wrong quotes
I see some problem here because plugin activates on multi-carets. IMO it should not. 

And this is a bug:

after this text and carets:

Screenshot from 2021-09-28 13-35-43

plugin CAN be activated and it gives BROKEN text (after choosing text "badge")
Screenshot from 2021-09-28 13-35-46

@halfbrained

### PR DESCRIPTION
**Pull request by veksha**
@Alexey-T and @eltonfabricio10

please test this PR.

+ fix https://github.com/CudaText-addons/cuda_bootstrap_complete/issues/1
+ fix https://github.com/halfbrained/cuda_bootstrap_complete/issues/22
+ feature: quotes auto closing

### CODE REVIEW

**Comment by Alexey-T** [comment]
In this case
```
<a href="" class="active |"></a>
<a href="" class="active |"></a>
<a href="" class="active |"></a>
<a href="" class="active |"></a>
```
plug must add new name after 'active' and Space! but now it replaces 'active'. Bootstrap allows n class names space-separated.

**Comment by veksha** [comment]
are you sure?
I see this in readme:
https://github.com/CudaText-addons/cuda_bootstrap_complete/blob/ed3db3643c52f9fb57a9a8ab468768f40e37df20/readme/readme.txt#L6-L8

I have not changed this logic. it works as before.

**Comment by eltonfabricio10** [comment]
@veksha is very difficult to do what @Alexey-T said?

**Comment by CudaText-addons** [comment]
veksha, then it is the FeatureReq, please try to add.

**Pull request merged**
